import { Brand } from "@/types";

export const brands: Brand[] = [
  // Nigerian Food Brands
  {
    id: "indomie",
    name: "Indomie",
    slug: "indomie",
    description: "Nigeria's most popular instant noodles brand",
    logo: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    website: "https://indomie.com.ng",
    countryOfOrigin: "Nigeria",
    isActive: true,
    productCount: 15,
  },
  {
    id: "dangote",
    name: "Dangote",
    slug: "dangote",
    description: "Leading Nigerian brand for rice, flour, and cement",
    logo: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    website: "https://dangote.com",
    countryOfOrigin: "Nigeria",
    isActive: true,
    productCount: 12,
  },
  {
    id: "golden-penny",
    name: "Golden Penny",
    slug: "golden-penny",
    description: "Premium Nigerian flour and pasta brand",
    logo: "https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    website: "https://goldenpenny.com",
    countryOfOrigin: "Nigeria",
    isActive: true,
    productCount: 8,
  },
  {
    id: "honeywell",
    name: "Honeywell",
    slug: "honeywell",
    description: "Quality Nigerian flour and food products",
    logo: "https://images.unsplash.com/photo-1576086213369-97a306d36557?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    countryOfOrigin: "Nigeria",
    isActive: true,
    productCount: 10,
  },
  {
    id: "grand-cereals",
    name: "Grand Cereals",
    slug: "grand-cereals",
    description: "Nigerian rice and grain processing company",
    logo: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    countryOfOrigin: "Nigeria",
    isActive: true,
    productCount: 6,
  },
  {
    id: "mama-gold",
    name: "Mama Gold",
    slug: "mama-gold",
    description: "Premium Nigerian rice brand",
    logo: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    countryOfOrigin: "Nigeria",
    isActive: true,
    productCount: 5,
  },
  {
    id: "gino",
    name: "Gino",
    slug: "gino",
    description: "Popular Nigerian tomato paste and spice brand",
    logo: "https://images.unsplash.com/photo-1592595896551-12b371d546d5?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    countryOfOrigin: "Nigeria",
    isActive: true,
    productCount: 12,
  },
  {
    id: "peak",
    name: "Peak",
    slug: "peak",
    description: "Leading milk and dairy products brand",
    logo: "https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    countryOfOrigin: "Nigeria",
    isActive: true,
    productCount: 8,
  },
  {
    id: "maggi",
    name: "Maggi",
    slug: "maggi",
    description: "Popular seasoning and cooking cubes",
    logo: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    website: "https://maggi.com.ng",
    countryOfOrigin: "Switzerland",
    isActive: true,
    productCount: 18,
  },
  {
    id: "knorr",
    name: "Knorr",
    slug: "knorr",
    description: "International seasoning and soup brand",
    logo: "https://images.unsplash.com/photo-1607672632458-9eb56696346b?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    website: "https://knorr.com",
    countryOfOrigin: "Germany",
    isActive: true,
    productCount: 16,
  },

  // Beverage Brands
  {
    id: "coca-cola",
    name: "Coca-Cola",
    slug: "coca-cola",
    description: "World's leading soft drink brand",
    logo: "https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    website: "https://coca-cola.com",
    countryOfOrigin: "United States",
    isActive: true,
    productCount: 8,
  },
  {
    id: "pepsi",
    name: "Pepsi",
    slug: "pepsi",
    description: "Popular cola and soft drink brand",
    logo: "https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    website: "https://pepsi.com",
    countryOfOrigin: "United States",
    isActive: true,
    productCount: 6,
  },
  {
    id: "five-alive",
    name: "Five Alive",
    slug: "five-alive",
    description: "Refreshing fruit juice blend",
    logo: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    countryOfOrigin: "Nigeria",
    isActive: true,
    productCount: 4,
  },
  {
    id: "chivita",
    name: "Chivita",
    slug: "chivita",
    description: "Premium fruit juices and drinks",
    logo: "https://images.unsplash.com/photo-1621447504864-d8686e12698c?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    countryOfOrigin: "Nigeria",
    isActive: true,
    productCount: 12,
  },
  {
    id: "hollandia",
    name: "Hollandia",
    slug: "hollandia",
    description: "Quality dairy and yogurt products",
    logo: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    countryOfOrigin: "Nigeria",
    isActive: true,
    productCount: 9,
  },
  {
    id: "milo",
    name: "Milo",
    slug: "milo",
    description: "Chocolate malt drink for energy",
    logo: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    website: "https://milo.com",
    countryOfOrigin: "Australia",
    isActive: true,
    productCount: 5,
  },

  // International Food Brands
  {
    id: "nestle",
    name: "Nestlé",
    slug: "nestle",
    description: "Global food and beverage company",
    logo: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    website: "https://nestle.com",
    countryOfOrigin: "Switzerland",
    isActive: true,
    productCount: 22,
  },
  {
    id: "unilever",
    name: "Unilever",
    slug: "unilever",
    description: "Leading consumer goods company",
    logo: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    website: "https://unilever.com",
    countryOfOrigin: "United Kingdom",
    isActive: true,
    productCount: 28,
  },
  {
    id: "dettol",
    name: "Dettol",
    slug: "dettol",
    description: "Trusted antibacterial and hygiene products",
    logo: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    website: "https://dettol.com",
    countryOfOrigin: "United Kingdom",
    isActive: true,
    productCount: 15,
  },
  {
    id: "close-up",
    name: "Close Up",
    slug: "close-up",
    description: "Fresh breath toothpaste brand",
    logo: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    website: "https://closeup.com",
    countryOfOrigin: "United States",
    isActive: true,
    productCount: 6,
  },

  // Premium Rice Brands
  {
    id: "uncle-bens",
    name: "Uncle Ben's",
    slug: "uncle-bens",
    description: "Premium rice and ready meals",
    logo: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    countryOfOrigin: "United States",
    isActive: true,
    productCount: 8,
  },
  {
    id: "tilda",
    name: "Tilda",
    slug: "tilda",
    description: "Premium basmati and specialty rice",
    logo: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    countryOfOrigin: "United Kingdom",
    isActive: true,
    productCount: 12,
  },

  // Snack Brands
  {
    id: "pringles",
    name: "Pringles",
    slug: "pringles",
    description: "Iconic stackable potato chips",
    logo: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    website: "https://pringles.com",
    countryOfOrigin: "United States",
    isActive: true,
    productCount: 10,
  },
  {
    id: "digestive",
    name: "Digestive",
    slug: "digestive",
    description: "Classic British biscuits",
    logo: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    countryOfOrigin: "United Kingdom",
    isActive: true,
    productCount: 5,
  },
  {
    id: "cabin",
    name: "Cabin",
    slug: "cabin",
    description: "Popular Nigerian biscuits and crackers",
    logo: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    countryOfOrigin: "Nigeria",
    isActive: true,
    productCount: 8,
  },

  // Cooking Oil Brands
  {
    id: "devon-kings",
    name: "Devon Kings",
    slug: "devon-kings",
    description: "Premium cooking oils and margarine",
    logo: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    countryOfOrigin: "Nigeria",
    isActive: true,
    productCount: 6,
  },
  {
    id: "grand-oil",
    name: "Grand Oil",
    slug: "grand-oil",
    description: "Quality vegetable cooking oils",
    logo: "https://images.unsplash.com/photo-1593113630400-ea4288922497?w=400&h=400&fit=crop&crop=entropy&auto=format&q=80",
    countryOfOrigin: "Nigeria",
    isActive: true,
    productCount: 4,
  },
];

export const featuredBrands = brands.filter(
  (brand) => brand.productCount >= 10,
);

export const getBrandBySlug = (slug: string) => {
  return brands.find((brand) => brand.slug === slug);
};

export const nigerianBrands = brands.filter(
  (brand) => brand.countryOfOrigin === "Nigeria",
);

export const internationalBrands = brands.filter(
  (brand) => brand.countryOfOrigin !== "Nigeria",
);
