import { type Address } from "@/types/addresses";

export const mockAddresses: Address[] = [
  {
    id: "1",
    firstName: "Hassan",
    lastName: "Umar",
    address1: "123 Main Street",
    address2: "Apt 4B",
    city: "Toronto",
    province: "ON",
    postalCode: "M5V 2H1",
    phone: "+1 (555) 123-4567",
    isDefault: true,
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: "2",
    firstName: "Nabeel",
    lastName: "Hassan",
    address1: "456 Queen Street West",
    address2: "Unit 12",
    city: "Toronto",
    province: "ON",
    postalCode: "M5V 2A9",
    phone: "+1 (555) 123-4567",
    isDefault: false,
    createdAt: "2024-02-20T14:15:00Z",
    updatedAt: "2024-02-20T14:15:00Z",
  },
  {
    id: "3",
    firstName: "John",
    lastName: "Doe",
    address1: "789 Yonge Street",
    address2: "Suite 300",
    city: "Toronto",
    province: "ON",
    postalCode: "M4W 2G8",
    phone: "+1 (555) 123-4567",
    isDefault: false,
    createdAt: "2024-03-10T09:45:00Z",
    updatedAt: "2024-03-10T09:45:00Z",
  },
];

export const canadianProvinces = [
  { code: "AB", name: "Alberta" },
  { code: "BC", name: "British Columbia" },
  { code: "MB", name: "Manitoba" },
  { code: "NB", name: "New Brunswick" },
  { code: "NL", name: "Newfoundland and Labrador" },
  { code: "NS", name: "Nova Scotia" },
  { code: "NT", name: "Northwest Territories" },
  { code: "NU", name: "Nunavut" },
  { code: "ON", name: "Ontario" },
  { code: "PE", name: "Prince Edward Island" },
  { code: "QC", name: "Quebec" },
  { code: "SK", name: "Saskatchewan" },
  { code: "YT", name: "Yukon" },
];
