export interface Location {
    id: string;
    city: string;
    province: string;
    country: string;
    postalCodes: string[];
    isServiceable: boolean;
    deliveryTimeMin: number;
    deliveryTimeMax: number;
    deliveryFee: number;
    freeDeliveryThreshold: number;
    coordinates: { latitude: number; longitude: number };
  }
  
  export const locations: Location[] = [
    {
      id: "toronto-on",
      city: "Toronto",
      province: "Ontario",
      country: "Canada",
      postalCodes: [
        "M1A",
        "M1B",
        "M1C",
        "M1E",
        "M1G",
        "M1H",
        "M1J",
        "M1K",
        "M1L",
        "M1M",
        "M1N",
        "M1P",
        "M1R",
        "M1S",
        "M1T",
        "M1V",
        "M1W",
        "M1X",
        "M2H",
        "M2J",
        "M2K",
        "M2L",
        "M2M",
        "M2N",
        "M2P",
        "M2R",
        "M3A",
        "M3B",
        "M3C",
        "M3H",
        "M3J",
        "M3K",
        "M3L",
        "M3M",
        "M3N",
        "M4A",
        "M4B",
        "M4C",
        "M4E",
        "M4G",
        "M4H",
        "M4J",
        "M4K",
        "M4L",
        "M4M",
        "M4N",
        "M4P",
        "M4R",
        "M4S",
        "M4T",
        "M4V",
        "M4W",
        "M4X",
        "M4Y",
        "M5A",
        "M5B",
        "M5C",
        "M5E",
        "M5G",
        "M5H",
        "M5J",
        "M5K",
        "M5L",
        "M5M",
        "M5N",
        "M5P",
        "M5R",
        "M5S",
        "M5T",
        "M5V",
        "M5W",
        "M5X",
        "M6A",
        "M6B",
        "M6C",
        "M6E",
        "M6G",
        "M6H",
        "M6J",
        "M6K",
        "M6L",
        "M6M",
        "M6N",
        "M6P",
        "M6R",
        "M6S",
        "M8V",
        "M8W",
        "M8X",
        "M8Y",
        "M8Z",
        "M9A",
        "M9B",
        "M9C",
        "M9L",
        "M9M",
        "M9N",
        "M9P",
        "M9R",
        "M9V",
        "M9W",
      ],
      isServiceable: true,
      deliveryTimeMin: 60,
      deliveryTimeMax: 120,
      deliveryFee: 4.99,
      freeDeliveryThreshold: 75,
      coordinates: { latitude: 43.6532, longitude: -79.3832 },
    },
    {
      id: "mississauga-on",
      city: "Mississauga",
      province: "Ontario",
      country: "Canada",
      postalCodes: [
        "L4T",
        "L4W",
        "L4X",
        "L4Y",
        "L4Z",
        "L5A",
        "L5B",
        "L5C",
        "L5E",
        "L5G",
        "L5H",
        "L5J",
        "L5K",
        "L5L",
        "L5M",
        "L5N",
        "L5R",
        "L5S",
        "L5T",
        "L5V",
        "L5W",
      ],
      isServiceable: true,
      deliveryTimeMin: 90,
      deliveryTimeMax: 150,
      deliveryFee: 6.99,
      freeDeliveryThreshold: 85,
      coordinates: { latitude: 43.589, longitude: -79.6441 },
    },
    {
      id: "brampton-on",
      city: "Brampton",
      province: "Ontario",
      country: "Canada",
      postalCodes: [
        "L6P",
        "L6R",
        "L6S",
        "L6T",
        "L6V",
        "L6W",
        "L6X",
        "L6Y",
        "L6Z",
        "L7A",
        "L7B",
        "L7C",
      ],
      isServiceable: true,
      deliveryTimeMin: 90,
      deliveryTimeMax: 150,
      deliveryFee: 6.99,
      freeDeliveryThreshold: 85,
      coordinates: { latitude: 43.7315, longitude: -79.7624 },
    },
    {
      id: "markham-on",
      city: "Markham",
      province: "Ontario",
      country: "Canada",
      postalCodes: ["L3P", "L3R", "L3S", "L3T", "L6B", "L6C", "L6E", "L6G"],
      isServiceable: true,
      deliveryTimeMin: 90,
      deliveryTimeMax: 150,
      deliveryFee: 6.99,
      freeDeliveryThreshold: 85,
      coordinates: { latitude: 43.8561, longitude: -79.337 },
    },
    {
      id: "ottawa-on",
      city: "Ottawa",
      province: "Ontario",
      country: "Canada",
      postalCodes: [
        "K1A",
        "K1B",
        "K1C",
        "K1E",
        "K1G",
        "K1H",
        "K1J",
        "K1K",
        "K1L",
        "K1M",
        "K1N",
        "K1P",
        "K1R",
        "K1S",
        "K1T",
        "K1V",
        "K1W",
        "K1X",
        "K1Y",
        "K1Z",
        "K2A",
        "K2B",
        "K2C",
        "K2E",
        "K2G",
        "K2H",
        "K2J",
        "K2K",
        "K2L",
        "K2M",
        "K2P",
        "K2R",
        "K2S",
        "K2T",
        "K2V",
        "K2W",
      ],
      isServiceable: true,
      deliveryTimeMin: 90,
      deliveryTimeMax: 180,
      deliveryFee: 7.99,
      freeDeliveryThreshold: 90,
      coordinates: { latitude: 45.4215, longitude: -75.6972 },
    },
    {
      id: "hamilton-on",
      city: "Hamilton",
      province: "Ontario",
      country: "Canada",
      postalCodes: [
        "L8E",
        "L8G",
        "L8H",
        "L8J",
        "L8K",
        "L8L",
        "L8M",
        "L8N",
        "L8P",
        "L8R",
        "L8S",
        "L8T",
        "L8V",
        "L8W",
        "L9A",
        "L9B",
        "L9C",
        "L9G",
        "L9H",
        "L9K",
      ],
      isServiceable: true,
      deliveryTimeMin: 120,
      deliveryTimeMax: 180,
      deliveryFee: 8.99,
      freeDeliveryThreshold: 95,
      coordinates: { latitude: 43.2557, longitude: -79.8711 },
    },
  
    // Quebec
    {
      id: "montreal-qc",
      city: "Montreal",
      province: "Quebec",
      country: "Canada",
      postalCodes: [
        "H1A",
        "H1B",
        "H1C",
        "H1E",
        "H1G",
        "H1H",
        "H1J",
        "H1K",
        "H1L",
        "H1M",
        "H1N",
        "H1P",
        "H1R",
        "H1S",
        "H1T",
        "H1V",
        "H1W",
        "H1X",
        "H1Y",
        "H1Z",
        "H2A",
        "H2B",
        "H2C",
        "H2E",
        "H2G",
        "H2H",
        "H2J",
        "H2K",
        "H2L",
        "H2M",
        "H2N",
        "H2P",
        "H2R",
        "H2S",
        "H2T",
        "H2V",
        "H2W",
        "H2X",
        "H2Y",
        "H2Z",
        "H3A",
        "H3B",
        "H3C",
        "H3E",
        "H3G",
        "H3H",
        "H3J",
        "H3K",
        "H3L",
        "H3M",
        "H3N",
        "H3P",
        "H3R",
        "H3S",
        "H3T",
        "H3V",
        "H3W",
        "H3X",
        "H3Y",
        "H3Z",
        "H4A",
        "H4B",
        "H4C",
        "H4E",
        "H4G",
        "H4H",
        "H4J",
        "H4K",
        "H4L",
        "H4M",
        "H4N",
        "H4P",
        "H4R",
        "H4S",
        "H4T",
        "H4V",
        "H4W",
        "H4X",
        "H4Y",
        "H4Z",
      ],
      isServiceable: true,
      deliveryTimeMin: 90,
      deliveryTimeMax: 150,
      deliveryFee: 6.99,
      freeDeliveryThreshold: 85,
      coordinates: { latitude: 45.5017, longitude: -73.5673 },
    },
    {
      id: "quebec-city-qc",
      city: "Quebec City",
      province: "Quebec",
      country: "Canada",
      postalCodes: [
        "G1A",
        "G1B",
        "G1C",
        "G1E",
        "G1G",
        "G1H",
        "G1J",
        "G1K",
        "G1L",
        "G1M",
        "G1N",
        "G1P",
        "G1R",
        "G1S",
        "G1T",
        "G1V",
        "G1W",
        "G1X",
        "G1Y",
        "G2A",
        "G2B",
        "G2C",
        "G2E",
        "G2G",
        "G2J",
        "G2K",
        "G2L",
        "G2M",
      ],
      isServiceable: true,
      deliveryTimeMin: 120,
      deliveryTimeMax: 180,
      deliveryFee: 8.99,
      freeDeliveryThreshold: 95,
      coordinates: { latitude: 46.8139, longitude: -71.208 },
    },
    {
      id: "laval-qc",
      city: "Laval",
      province: "Quebec",
      country: "Canada",
      postalCodes: [
        "H7A",
        "H7B",
        "H7C",
        "H7E",
        "H7G",
        "H7H",
        "H7J",
        "H7K",
        "H7L",
        "H7M",
        "H7N",
        "H7P",
        "H7R",
        "H7S",
        "H7T",
        "H7V",
        "H7W",
        "H7X",
        "H7Y",
      ],
      isServiceable: true,
      deliveryTimeMin: 90,
      deliveryTimeMax: 150,
      deliveryFee: 6.99,
      freeDeliveryThreshold: 85,
      coordinates: { latitude: 45.6066, longitude: -73.7124 },
    },
  
    // British Columbia
    {
      id: "vancouver-bc",
      city: "Vancouver",
      province: "British Columbia",
      country: "Canada",
      postalCodes: [
        "V5A",
        "V5B",
        "V5C",
        "V5E",
        "V5G",
        "V5H",
        "V5J",
        "V5K",
        "V5L",
        "V5M",
        "V5N",
        "V5P",
        "V5R",
        "V5S",
        "V5T",
        "V5V",
        "V5W",
        "V5X",
        "V5Y",
        "V5Z",
        "V6A",
        "V6B",
        "V6C",
        "V6E",
        "V6G",
        "V6H",
        "V6J",
        "V6K",
        "V6L",
        "V6M",
        "V6N",
        "V6P",
        "V6R",
        "V6S",
        "V6T",
        "V6V",
        "V6W",
        "V6X",
        "V6Y",
        "V6Z",
        "V7A",
        "V7B",
        "V7C",
      ],
      isServiceable: true,
      deliveryTimeMin: 90,
      deliveryTimeMax: 150,
      deliveryFee: 6.99,
      freeDeliveryThreshold: 85,
      coordinates: { latitude: 49.2827, longitude: -123.1207 },
    },
    {
      id: "burnaby-bc",
      city: "Burnaby",
      province: "British Columbia",
      country: "Canada",
      postalCodes: ["V3J", "V3N", "V5A", "V5B", "V5C", "V5E", "V5G", "V5H"],
      isServiceable: true,
      deliveryTimeMin: 90,
      deliveryTimeMax: 150,
      deliveryFee: 6.99,
      freeDeliveryThreshold: 85,
      coordinates: { latitude: 49.2488, longitude: -122.9805 },
    },
    {
      id: "richmond-bc",
      city: "Richmond",
      province: "British Columbia",
      country: "Canada",
      postalCodes: ["V6W", "V6X", "V6Y", "V7A", "V7B", "V7C", "V7E"],
      isServiceable: true,
      deliveryTimeMin: 90,
      deliveryTimeMax: 150,
      deliveryFee: 6.99,
      freeDeliveryThreshold: 85,
      coordinates: { latitude: 49.1666, longitude: -123.1336 },
    },
  
    // Alberta
    {
      id: "calgary-ab",
      city: "Calgary",
      province: "Alberta",
      country: "Canada",
      postalCodes: [
        "T1X",
        "T1Y",
        "T2A",
        "T2B",
        "T2C",
        "T2E",
        "T2G",
        "T2H",
        "T2J",
        "T2K",
        "T2L",
        "T2M",
        "T2N",
        "T2P",
        "T2R",
        "T2S",
        "T2T",
        "T2V",
        "T2W",
        "T2X",
        "T2Y",
        "T2Z",
        "T3A",
        "T3B",
        "T3C",
        "T3E",
        "T3G",
        "T3H",
        "T3J",
        "T3K",
        "T3L",
        "T3M",
        "T3N",
        "T3P",
        "T3R",
        "T3S",
      ],
      isServiceable: true,
      deliveryTimeMin: 120,
      deliveryTimeMax: 180,
      deliveryFee: 8.99,
      freeDeliveryThreshold: 95,
      coordinates: { latitude: 51.0447, longitude: -114.0719 },
    },
    {
      id: "edmonton-ab",
      city: "Edmonton",
      province: "Alberta",
      country: "Canada",
      postalCodes: [
        "T5A",
        "T5B",
        "T5C",
        "T5E",
        "T5G",
        "T5H",
        "T5J",
        "T5K",
        "T5L",
        "T5M",
        "T5N",
        "T5P",
        "T5R",
        "T5S",
        "T5T",
        "T5V",
        "T5W",
        "T5X",
        "T5Y",
        "T5Z",
        "T6A",
        "T6B",
        "T6C",
        "T6E",
        "T6G",
        "T6H",
        "T6J",
        "T6K",
        "T6L",
        "T6M",
        "T6N",
        "T6P",
        "T6R",
        "T6S",
        "T6T",
        "T6V",
        "T6W",
        "T6X",
      ],
      isServiceable: true,
      deliveryTimeMin: 120,
      deliveryTimeMax: 180,
      deliveryFee: 8.99,
      freeDeliveryThreshold: 95,
      coordinates: { latitude: 53.5444, longitude: -113.4909 },
    },
  
    // Manitoba
    {
      id: "winnipeg-mb",
      city: "Winnipeg",
      province: "Manitoba",
      country: "Canada",
      postalCodes: [
        "R2C",
        "R2G",
        "R2H",
        "R2J",
        "R2K",
        "R2L",
        "R2M",
        "R2N",
        "R2P",
        "R2R",
        "R2V",
        "R2W",
        "R2X",
        "R2Y",
        "R3A",
        "R3B",
        "R3C",
        "R3E",
        "R3G",
        "R3H",
        "R3J",
        "R3K",
        "R3L",
        "R3M",
        "R3N",
        "R3P",
        "R3R",
        "R3S",
        "R3T",
        "R3V",
        "R3W",
        "R3X",
        "R3Y",
      ],
      isServiceable: true,
      deliveryTimeMin: 120,
      deliveryTimeMax: 200,
      deliveryFee: 9.99,
      freeDeliveryThreshold: 100,
      coordinates: { latitude: 49.8951, longitude: -97.1384 },
    },
  
    // Nova Scotia
    {
      id: "halifax-ns",
      city: "Halifax",
      province: "Nova Scotia",
      country: "Canada",
      postalCodes: [
        "B2Y",
        "B3A",
        "B3B",
        "B3E",
        "B3G",
        "B3H",
        "B3J",
        "B3K",
        "B3L",
        "B3M",
        "B3N",
        "B3P",
        "B3R",
        "B3S",
        "B3T",
        "B3V",
        "B3W",
        "B3Z",
        "B4A",
        "B4B",
        "B4C",
        "B4E",
        "B4G",
        "B4H",
      ],
      isServiceable: true,
      deliveryTimeMin: 120,
      deliveryTimeMax: 200,
      deliveryFee: 9.99,
      freeDeliveryThreshold: 100,
      coordinates: { latitude: 44.6488, longitude: -63.5752 },
    },
  ];
  
  export const provinces = [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Northwest Territories",
    "Nova Scotia",
    "Nunavut",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Yukon",
  ];
  
  export const getLocationsByProvince = (province: string) => {
    return locations.filter((location) => location.province === province);
  };
  
  export const getLocationById = (id: string) => {
    return locations.find((location) => location.id === id);
  };
  
  export const isPostalCodeServiceable = (postalCode: string) => {
    const normalizedCode = postalCode
      .toUpperCase()
      .replace(/\s/g, "")
      .substring(0, 3);
    return locations.some((location) =>
      location.postalCodes.some((code) => code === normalizedCode),
    );
  };
  
  export const getLocationByPostalCode = (postalCode: string) => {
    const normalizedCode = postalCode
      .toUpperCase()
      .replace(/\s/g, "")
      .substring(0, 3);
    return locations.find((location) =>
      location.postalCodes.some((code) => code === normalizedCode),
    );
  };